spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    kafkaOrderTopic: "order-topic"
    kafkaOrderStatusTopic: "order-status-topic"
    kafkaMessageGroupId: "kafka-message-group-id"
